Furry Potato: party Class Reference
party Class Reference
PartyController singleton
Public Member Functions
override void _Ready ()
void StartParty (string id)
Starts party
bool CheckIfPartyWasDone (string id)
Returns bool whether party has been played or not
Dictionary< string, string > GetPartyRatings ()
Returns ratings of all done partys
Public Attributes
string[] PartyIds = { "0", "1", "2", "3", "4",}
List of all partys' id's
Private Member Functions
delegate void PartyEnded (int id, int money, int experience, int musicQuality)
PartyEnded signal. Emitted with parameters, when party has finished.
Dictionary< string, int > ComputePartyRewards (string id)
Calculates rewards for party
void AnimationPlayerAnimFinished (string animName)
Callback for AnimationPlayer's '_on_animation_finished' signal
void EndParty ()
Method ends party executing required callbacks
void AddPartyRating (string partyId, Dictionary< string, string > ratingData)
Adds party rating to database
Private Attributes
AnimationPlayer _animationPlayer
AnimationPlayer node instance
string _currentPartyId = ""
Holds string id of currently played party
Label _label
Label instance
ColorRect _colorRect
ColorRect instance
readonly string[] _donePartys = new string[] { }
List of all done partys
readonly Dictionary< string, string > _partyRatings = new Dictionary<string, string>()
Contains data of all party ratings
readonly Dictionary< string, int > PartyData
Contains data of all of the partys
Detailed Description
PartyController singleton
Todo:
needs GameController to be rewritten to C# to work properly
Definition at line 10 of file party.cs.
Member Function Documentation
_Ready()
override void party._Ready () inline
Definition at line 84 of file party.cs.
References _animationPlayer, _colorRect, and _label.
AddPartyRating()
void party.AddPartyRating (string partyId, Dictionary< string, string > ratingData) inline private
Adds party rating to database
Parameters
partyId Party id
ratingData Rating data
Definition at line 170 of file party.cs.
References _partyRatings.
Referenced by EndParty().
AnimationPlayerAnimFinished()
void party.AnimationPlayerAnimFinished (string animName) inline private
Callback for AnimationPlayer's '_on_animation_finished' signal
Parameters
animName Name of finished animation
Definition at line 139 of file party.cs.
References _colorRect, _label, and EndParty().
CheckIfPartyWasDone()
bool party.CheckIfPartyWasDone (string id) inline
Returns bool whether party has been played or not
Parameters
id Party id
Returns
true or false
Definition at line 185 of file party.cs.
References _donePartys.
ComputePartyRewards()
Dictionary< string, int > party.ComputePartyRewards (string id) inline private
Calculates rewards for party
Parameters
id Party id
Returns
Dictionary of calculated data
Todo:
Rewrite GameController to C# to properly access it's variables
Definition at line 110 of file party.cs.
References PartyData.
Referenced by EndParty().
EndParty()
void party.EndParty () inline private
Method ends party executing required callbacks
Exceptions
ArgumentNullException Null exception whether PartyRewards weren't computed properly
Todo:
Add getting data from GameController singleton when it will be rewritten to C#
Definition at line 152 of file party.cs.
References _currentPartyId, AddPartyRating(), and ComputePartyRewards().
Referenced by AnimationPlayerAnimFinished().
GetPartyRatings()
Dictionary< string, string > party.GetPartyRatings () inline
Returns ratings of all done partys
Returns
Dictionary of rating data
Definition at line 193 of file party.cs.
References _partyRatings.
PartyEnded()
delegate void party.PartyEnded (int id, int money, int experience, int musicQuality) private
PartyEnded signal. Emitted with parameters, when party has finished.
Todo:
change signal name in the rest of code from "party_ended" to "PartyEnded"
StartParty()
void party.StartParty (string id) inline
Starts party
Parameters
id Party id
Definition at line 97 of file party.cs.
References _animationPlayer, _colorRect, _currentPartyId, and _label.
Member Data Documentation
_animationPlayer
AnimationPlayer party._animationPlayer private
AnimationPlayer node instance
Definition at line 22 of file party.cs.
Referenced by _Ready(), and StartParty().
_colorRect
ColorRect party._colorRect private
ColorRect instance
Definition at line 37 of file party.cs.
Referenced by _Ready(), AnimationPlayerAnimFinished(), and StartParty().
_currentPartyId
string party._currentPartyId = "" private
Holds string id of currently played party
Definition at line 27 of file party.cs.
Referenced by EndParty(), and StartParty().
_donePartys
readonly string [] party._donePartys = new string[] { } private
List of all done partys
Definition at line 42 of file party.cs.
Referenced by CheckIfPartyWasDone().
_label
Label party._label private
Label instance
Definition at line 32 of file party.cs.
Referenced by _Ready(), AnimationPlayerAnimFinished(), and StartParty().
_partyRatings
readonly Dictionary<string, string> party._partyRatings = new Dictionary<string, string>() private
Contains data of all party ratings
Definition at line 52 of file party.cs.
Referenced by AddPartyRating(), and GetPartyRatings().
PartyData
readonly Dictionary<string, int> party.PartyData private
Initial value:
= new Dictionary<string, int>() {
        ["0_club_id"] = 0,
        ["0_base_price"] = 1000,
        ["0_base_experience"] = 100,
        ["0_req_experience"] = 0,
        ["1_club_id"] = 1,
        ["1_base_price"] = 1000,
        ["1_base_experience"] = 150,
        ["1_req_experience"] = 10,
        ["2_club_id"] = 2,
        ["2_base_price"] = 1000,
        ["2_base_experience"] = 170,
        ["2_req_experience"] = 200,
        ["3_club_id"] = 3,
        ["3_base_price"] = 1000,
        ["3_base_experience"] = 120,
        ["3_req_experience"] = 300,
        ["4_club_id"] = 4,
        ["4_base_price"] = 100,
        ["4_base_experience"] = 400,
        ["4_req_experience"] = 450,
    }
Contains data of all of the partys
Definition at line 57 of file party.cs.
Referenced by ComputePartyRewards().
PartyIds
string [] party.PartyIds = { "0", "1", "2", "3", "4",}
List of all partys' id's
Definition at line 47 of file party.cs.
The documentation for this class was generated from the following file:
party.cs