Furry Potato: OptionSaver Class Reference
OptionSaver Class Reference
Class used to save and load game options
Public Member Functions
void SaveOptions (Dictionary< string, Dictionary< string, string > > data)
Method tor saving options
void PreloadOptions ()
Method that we use to preload option data
Public Attributes
Dictionary< string, Dictionary< string, string > > PreloadedOptionSaveData = new Dictionary<string, Dictionary<string, string>>()
String and string-dictionary dictionary that holds preloaded option data.
Private Member Functions
delegate void OptionSaveDataPreloaded ()
Signal emitted, when save options have been preloaded.
Private Attributes
readonly DictionaryConverter _dc = new DictionaryConverter()
NewDEVSharp.Collections.DictionaryConverter instance
readonly SaveContainer _saveContainer = new SaveContainer()
SaveContainer instance
Detailed Description
Class used to save and load game options
Definition at line 11 of file OptionSaver.cs.
Member Function Documentation
OptionSaveDataPreloaded()
delegate void OptionSaver.OptionSaveDataPreloaded () private
Signal emitted, when save options have been preloaded.
Use PreloadedOptionSaveData to access them.
PreloadOptions()
void OptionSaver.PreloadOptions () inline
Method that we use to preload option data
It fills out PreloadedOptionSaveData variable with found save data and emits OptionSaveDataPreload signal.
Definition at line 55 of file OptionSaver.cs.
References Loader.LoadSave(), and PreloadedOptionSaveData.
SaveOptions()
void OptionSaver.SaveOptions (Dictionary< string, Dictionary< string, string > > data) inline
Method tor saving options
Parameters
data Dictionary of options data to dave
Definition at line 40 of file OptionSaver.cs.
References _dc, _saveContainer, NewDEVSharp.Collections.DictionaryConverter.GodotToSystem(), SaveContainer.SetSaveDir(), SaveContainer.WriteData(), and SaveContainer.WriteDirectories().
Member Data Documentation
_dc
readonly DictionaryConverter OptionSaver._dc = new DictionaryConverter() private
NewDEVSharp.Collections.DictionaryConverter instance
Definition at line 23 of file OptionSaver.cs.
Referenced by SaveOptions().
_saveContainer
readonly SaveContainer OptionSaver._saveContainer = new SaveContainer() private
SaveContainer instance
Definition at line 34 of file OptionSaver.cs.
Referenced by SaveOptions().
PreloadedOptionSaveData
Dictionary<string, Dictionary<string, string> > OptionSaver.PreloadedOptionSaveData = new Dictionary<string, Dictionary<string, string>>()
String and string-dictionary dictionary that holds preloaded option data.
If the PreloadOptions method haven't been called yet, this dictionary is null
Definition at line 29 of file OptionSaver.cs.
Referenced by PreloadOptions().
The documentation for this class was generated from the following file:
OptionSaver.cs