Furry Potato: Saver Class Reference
Saver Class Reference
Public Member Functions
override void _Ready ()
void SaveGame (Dictionary< string, Dictionary< string, string > > data, string dir, string orgSName)
This method calls SaveContainer class to save data
Private Member Functions
System.Collections.Generic.Dictionary< string, string > GodotToSystem (Godot.Collections.Dictionary< string, string > dict)
This function converts Godot dictionary to the system one
Private Attributes
readonly SaveContainer _saveContainer = new SaveContainer()
Detailed Description
Definition at line 7 of file Saver.cs.
Member Function Documentation
_Ready()
override void Saver._Ready () inline
Definition at line 14 of file Saver.cs.
GodotToSystem()
System.Collections.Generic.Dictionary< string, string > Saver.GodotToSystem (Godot.Collections.Dictionary< string, string > dict) inline private
This function converts Godot dictionary to the system one
This uses string as both data types
Parameters
dict Godot Dictionary, with strings as both data types
Returns
The same dictionary, as
System.Collections.Generic.Dictionary
Definition at line 41 of file Saver.cs.
Referenced by SaveGame().
SaveGame()
void Saver.SaveGame (Dictionary< string, Dictionary< string, string > > data, string dir, string orgSName) inline
This method calls SaveContainer class to save data
Parameters
data Save data
dir Save root directory
orgSName Name of the save
Definition at line 25 of file Saver.cs.
References _saveContainer, GodotToSystem(), SaveContainer.SetSaveDir(), SaveContainer.WriteData(), and SaveContainer.WriteDirectories().
Member Data Documentation
_saveContainer
readonly SaveContainer Saver._saveContainer = new SaveContainer() private
Definition at line 8 of file Saver.cs.
Referenced by SaveGame().
The documentation for this class was generated from the following file:
Saver.cs