Furry Potato: CustomAudioLibrary Class Reference
CustomAudioLibrary Class Reference
Class used to manage all actions related to playing music from user's PC
Public Member Functions
override void _Ready ()
string[] LoadSongFiles ()
Loads for ust list of files that will be returned to godot in order to shuffle them
Private Member Functions
void InitFolderList ()
Called to initialize folder list
Private Attributes
readonly FolderBase _systemMusic = new FolderSystemMusic()
readonly FolderBase _systemDocuments = new FolderSystemDocuments()
readonly DataTags _dataTags = new DataTags()
readonly Dictionary< string, string > _folderList = new Dictionary<string, string>()
Dictionary of folders to look for music files
Detailed Description
Class used to manage all actions related to playing music from user's PC
Definition at line 12 of file CustomAudioLibrary.cs.
Member Function Documentation
_Ready()
override void CustomAudioLibrary._Ready () inline
Definition at line 31 of file CustomAudioLibrary.cs.
References InitFolderList().
InitFolderList()
void CustomAudioLibrary.InitFolderList () inline private
Called to initialize folder list
Definition at line 25 of file CustomAudioLibrary.cs.
References _folderList.
Referenced by _Ready().
LoadSongFiles()
string[] CustomAudioLibrary.LoadSongFiles () inline
Loads for ust list of files that will be returned to godot in order to shuffle them
Returns
Array of file paths
Definition at line 39 of file CustomAudioLibrary.cs.
References _dataTags, _folderList, FolderBase.GetFolderPath(), and NewDEVSharp.Utils.MP3.DataTags.Image().
Member Data Documentation
_dataTags
readonly DataTags CustomAudioLibrary._dataTags = new DataTags() private
Definition at line 16 of file CustomAudioLibrary.cs.
Referenced by LoadSongFiles().
_folderList
readonly Dictionary<string, string> CustomAudioLibrary._folderList = new Dictionary<string, string>() private
Dictionary of folders to look for music files
Definition at line 20 of file CustomAudioLibrary.cs.
Referenced by InitFolderList(), and LoadSongFiles().
_systemDocuments
readonly FolderBase CustomAudioLibrary._systemDocuments = new FolderSystemDocuments() private
Definition at line 15 of file CustomAudioLibrary.cs.
_systemMusic
readonly FolderBase CustomAudioLibrary._systemMusic = new FolderSystemMusic() private
Definition at line 14 of file CustomAudioLibrary.cs.
The documentation for this class was generated from the following file:
CustomAudioLibrary.cs