Furry Potato: DialogicSharp Class Reference
DialogicSharp Class Reference
Static Public Member Functions
static Node Start (String timeline="", String default_timeline="", bool useCanvasInstead=true)
static T Start< T > (String timeline="", String default_timeline="", String dialogScenePath="", bool useCanvasInstead=true)
static void Load (String slot_name="")
static void Save (String slot_name="")
static GC.Array GetSlotNames ()
static void EraseSlot (String slot_name)
static bool HasCurrentDialogNode ()
static void ResetSaves ()
static String GetCurrentSlot ()
static GC.Dictionary Export ()
static void Import (GC.Dictionary data)
static String GetVariable (String name)
static void SetVariable (String name, String value)
Properties
static String CurrentTimeline [get, set]
static GC.Dictionary Definitions [get]
static GC.Dictionary DefaultDefinitions [get]
static bool Autosave [get, set]
Static Private Attributes
static Script _dialogic = GD.Load<Script>("res://addons/dialogic/Other/DialogicClass.gd")
const String DEFAULT_DIALOG_RESOURCE = "res://addons/dialogic/Nodes/DialogNode.tscn"
Detailed Description
Definition at line 5 of file DialogicSharp.cs.
Member Function Documentation
EraseSlot()
static void DialogicSharp.EraseSlot (String slot_name) inline static
Definition at line 39 of file DialogicSharp.cs.
References _dialogic.
Export()
static GC.Dictionary DialogicSharp.Export () inline static
Definition at line 62 of file DialogicSharp.cs.
References _dialogic.
GetCurrentSlot()
static String DialogicSharp.GetCurrentSlot () inline static
Definition at line 54 of file DialogicSharp.cs.
References _dialogic.
GetSlotNames()
static GC.Array DialogicSharp.GetSlotNames () inline static
Definition at line 34 of file DialogicSharp.cs.
References _dialogic.
GetVariable()
static String DialogicSharp.GetVariable (String name) inline static
Definition at line 75 of file DialogicSharp.cs.
References _dialogic.
HasCurrentDialogNode()
static bool DialogicSharp.HasCurrentDialogNode () inline static
Definition at line 44 of file DialogicSharp.cs.
References _dialogic.
Import()
static void DialogicSharp.Import (GC.Dictionary data) inline static
Definition at line 67 of file DialogicSharp.cs.
References _dialogic.
Load()
static void DialogicSharp.Load (String slot_name = "") inline static
Definition at line 24 of file DialogicSharp.cs.
References _dialogic.
ResetSaves()
static void DialogicSharp.ResetSaves () inline static
Definition at line 49 of file DialogicSharp.cs.
References _dialogic.
Save()
static void DialogicSharp.Save (String slot_name = "") inline static
Definition at line 29 of file DialogicSharp.cs.
References _dialogic.
SetVariable()
static void DialogicSharp.SetVariable (String name, String value) inline static
Definition at line 80 of file DialogicSharp.cs.
References _dialogic.
Start()
static Node DialogicSharp.Start (String timeline = "", String default_timeline = "", bool useCanvasInstead = true) inline static
Definition at line 11 of file DialogicSharp.cs.
References DEFAULT_DIALOG_RESOURCE.
Start< T >()
static T DialogicSharp.Start< T > (String timeline = "", String default_timeline = "", String dialogScenePath = "", bool useCanvasInstead = true) inline static
Type Constraints
T : class
Definition at line 16 of file DialogicSharp.cs.
References _dialogic.
Member Data Documentation
_dialogic
Script DialogicSharp._dialogic = GD.Load<Script>("res://addons/dialogic/Other/DialogicClass.gd") static private
Definition at line 7 of file DialogicSharp.cs.
Referenced by EraseSlot(), Export(), GetCurrentSlot(), GetSlotNames(), GetVariable(), HasCurrentDialogNode(), Import(), Load(), ResetSaves(), Save(), SetVariable(), and Start< T >().
DEFAULT_DIALOG_RESOURCE
const String DialogicSharp.DEFAULT_DIALOG_RESOURCE = "res://addons/dialogic/Nodes/DialogNode.tscn" static private
Definition at line 8 of file DialogicSharp.cs.
Referenced by Start().
Property Documentation
Autosave
bool DialogicSharp.Autosave static get set
Definition at line 116 of file DialogicSharp.cs.
CurrentTimeline
String DialogicSharp.CurrentTimeline static get set
Definition at line 88 of file DialogicSharp.cs.
DefaultDefinitions
GC.Dictionary DialogicSharp.DefaultDefinitions static get
Definition at line 108 of file DialogicSharp.cs.
Definitions
GC.Dictionary DialogicSharp.Definitions static get
Definition at line 100 of file DialogicSharp.cs.
The documentation for this class was generated from the following file:
DialogicSharp.cs