Furry Potato: FurryPotato.Utils.UI.Dialogue Class Reference
FurryPotato.Utils.UI.Dialogue Class Reference
Class for handling dialogues.
Public Member Functions
delegate void DialogueEndedEventHandler (string dialogueName)
Signal emitted when dialogue ends.
delegate void DialogueStartedEventHandler ()
Signal emitted when dialogue starts.
delegate void EnterPressedEventHandler ()
Signal emitted when player presses enter or space.
override void _Ready ()
Method called when the node enters the scene tree for the first time.
override void _Input (InputEvent @event)
Handles pressing keys on the dialogue.
void StartDialogue (DialogueLine dialogueLine)
Checks if dialogue can be played and if so, plays it.
void HandleChoice (int choice)
This method handles player's choice and starts another part of dialogue based on the choice.
void EndDialogue ()
Ends dialogue.
Private Member Functions
void ShowChoicesAfterCurrentLine (DialogueLine dialogueLine, int currentLine)
Method that display choices on the screen after current line.
async void DisplayLineByLine (DialogueLine dialogueLine)
Method used to display one dialogue line.
Private Attributes
readonly IEnumerable< IDialogueCharacter > _characters = Array.Empty<IDialogueCharacter>()
Array of all available characters.
ItemList _choicesContainer
Container for choices.
PopupPanel _choicesPanel
Panel for choices.
DialogueLine _currentDialogueLine
Current dialogue line.
int _currentLineIndex
Index of current line.
Label _dialogueCharacterName
Label that displays character name in dialogues.
RichTextLabel _dialogueText
Rich text array that displays the text.
Detailed Description
Class for handling dialogues.
Copyright
New DEV
Author
DoS
Date
2023-08-27
Todo:
Create dialogue's UI
Handle dialogue lines
Handle characters
Handle character validation
Attention
This is still under development and might be unstable. There might be a lot of work with that
Definition at line 24 of file Dialogue.cs.
Member Function Documentation
_Input()
override void FurryPotato.Utils.UI.Dialogue._Input (InputEvent @ event) inline
Handles pressing keys on the dialogue.
Parameters
event InputEvent instance
Definition at line 96 of file Dialogue.cs.
References FurryPotato.Utils.UI.Dialogue._dialogueText.
_Ready()
override void FurryPotato.Utils.UI.Dialogue._Ready () inline
Method called when the node enters the scene tree for the first time.
Todo:
Add dialogues from their classes to _lines array
Definition at line 82 of file Dialogue.cs.
References FurryPotato.Utils.UI.Dialogue._choicesContainer, FurryPotato.Utils.UI.Dialogue._choicesPanel, FurryPotato.Utils.UI.Dialogue._dialogueCharacterName, and FurryPotato.Utils.UI.Dialogue._dialogueText.
DialogueEndedEventHandler()
delegate void FurryPotato.Utils.UI.Dialogue.DialogueEndedEventHandler (string dialogueName)
Signal emitted when dialogue ends.
DialogueStartedEventHandler()
delegate void FurryPotato.Utils.UI.Dialogue.DialogueStartedEventHandler ()
Signal emitted when dialogue starts.
DisplayLineByLine()
async void FurryPotato.Utils.UI.Dialogue.DisplayLineByLine (DialogueLine dialogueLine) inline private
Method used to display one dialogue line.
Parameters
dialogueLine Dialogue to get lines from
Definition at line 141 of file Dialogue.cs.
References FurryPotato.Utils.UI.Dialogue._dialogueText, FurryPotato.Utils.UI.DialogueLine.Characters, FurryPotato.Utils.UI.Dialogue.EndDialogue(), FurryPotato.Utils.UI.DialogueLine.Lines, and FurryPotato.Utils.UI.Dialogue.ShowChoicesAfterCurrentLine().
Referenced by FurryPotato.Utils.UI.Dialogue.StartDialogue().
EndDialogue()
void FurryPotato.Utils.UI.Dialogue.EndDialogue () inline
Ends dialogue.
Definition at line 172 of file Dialogue.cs.
References FurryPotato.Utils.UI.Dialogue._currentDialogueLine, and FurryPotato.Utils.UI.DialogueLine.Name.
Referenced by FurryPotato.Utils.UI.Dialogue.DisplayLineByLine(), and FurryPotato.Utils.UI.Dialogue.HandleChoice().
EnterPressedEventHandler()
delegate void FurryPotato.Utils.UI.Dialogue.EnterPressedEventHandler ()
Signal emitted when player presses enter or space.
HandleChoice()
void FurryPotato.Utils.UI.Dialogue.HandleChoice (int choice) inline
This method handles player's choice and starts another part of dialogue based on the choice.
Parameters
choice Choice name/id
Todo:
Handle choices
Definition at line 118 of file Dialogue.cs.
References FurryPotato.Utils.UI.Dialogue._currentDialogueLine, FurryPotato.Utils.UI.Dialogue.EndDialogue(), and FurryPotato.Utils.UI.DialogueLine.Name.
ShowChoicesAfterCurrentLine()
void FurryPotato.Utils.UI.Dialogue.ShowChoicesAfterCurrentLine (DialogueLine dialogueLine, int currentLine) inline private
Method that display choices on the screen after current line.
Parameters
dialogueLine Dialogue to get the choices from
currentLine Current line of the dialogue
Todo:
Handle choice displaying
Definition at line 128 of file Dialogue.cs.
References FurryPotato.Utils.UI.Dialogue._choicesContainer, FurryPotato.Utils.UI.Dialogue._choicesPanel, and FurryPotato.Utils.UI.DialogueLine.Choices.
Referenced by FurryPotato.Utils.UI.Dialogue.DisplayLineByLine().
StartDialogue()
void FurryPotato.Utils.UI.Dialogue.StartDialogue (DialogueLine dialogueLine) inline
Checks if dialogue can be played and if so, plays it.
Parameters
dialogueLine Name of the dialogue
Todo:
Handle dialogue playing
Definition at line 106 of file Dialogue.cs.
References FurryPotato.Utils.UI.Dialogue._currentDialogueLine, and FurryPotato.Utils.UI.Dialogue.DisplayLineByLine().
Referenced by FurryPotato.Game.Game._Ready().
Member Data Documentation
_characters
readonly IEnumerable<IDialogueCharacter> FurryPotato.Utils.UI.Dialogue._characters = Array.Empty<IDialogueCharacter>() private
Array of all available characters.
Definition at line 46 of file Dialogue.cs.
_choicesContainer
ItemList FurryPotato.Utils.UI.Dialogue._choicesContainer private
Container for choices.
Definition at line 51 of file Dialogue.cs.
Referenced by FurryPotato.Utils.UI.Dialogue._Ready(), and FurryPotato.Utils.UI.Dialogue.ShowChoicesAfterCurrentLine().
_choicesPanel
PopupPanel FurryPotato.Utils.UI.Dialogue._choicesPanel private
Panel for choices.
Definition at line 56 of file Dialogue.cs.
Referenced by FurryPotato.Utils.UI.Dialogue._Ready(), and FurryPotato.Utils.UI.Dialogue.ShowChoicesAfterCurrentLine().
_currentDialogueLine
DialogueLine FurryPotato.Utils.UI.Dialogue._currentDialogueLine private
Current dialogue line.
Definition at line 61 of file Dialogue.cs.
Referenced by FurryPotato.Utils.UI.Dialogue.EndDialogue(), FurryPotato.Utils.UI.Dialogue.HandleChoice(), and FurryPotato.Utils.UI.Dialogue.StartDialogue().
_currentLineIndex
int FurryPotato.Utils.UI.Dialogue._currentLineIndex private
Index of current line.
Definition at line 66 of file Dialogue.cs.
_dialogueCharacterName
Label FurryPotato.Utils.UI.Dialogue._dialogueCharacterName private
Label that displays character name in dialogues.
Definition at line 71 of file Dialogue.cs.
Referenced by FurryPotato.Utils.UI.Dialogue._Ready().
_dialogueText
RichTextLabel FurryPotato.Utils.UI.Dialogue._dialogueText private
Rich text array that displays the text.
Definition at line 76 of file Dialogue.cs.
Referenced by FurryPotato.Utils.UI.Dialogue._Input(), FurryPotato.Utils.UI.Dialogue._Ready(), and FurryPotato.Utils.UI.Dialogue.DisplayLineByLine().
The documentation for this class was generated from the following file:
Dialogue.cs