Furry Potato: NewDEVSharp.DLC.Manager Class Reference
NewDEVSharp.DLC.Manager Class Reference
Class used to manage all DLC related things in games.
Public Member Functions
override bool ClassInit ()
Class initializer.
DLC PreLoadDLCData (string path)
Preloads DLC Data into returned DLC class instance.
override string ClassName ()
Class name.
abstract bool ClassInit ()
Class initializer.
abstract string ClassName ()
Class name.
Private Attributes
readonly Verifier _verifier = new Verifier()
Verifier class instance.
readonly DLC _dlc = new DLC()
DLC class instance.
Detailed Description
Class used to manage all DLC related things in games.
Definition at line 7 of file DLC/Manager.cs.
Member Function Documentation
ClassInit()
override bool NewDEVSharp.DLC.Manager.ClassInit () inline virtual
Class initializer.
Returns
true or false whether class was initialized properly or not
Implements NewDEVSharp.BaseClass.
Definition at line 20 of file DLC/Manager.cs.
ClassName()
override string NewDEVSharp.DLC.Manager.ClassName () inline virtual
Class name.
Returns
Name of the class
Implements NewDEVSharp.BaseClass.
Definition at line 44 of file DLC/Manager.cs.
PreLoadDLCData()
DLC NewDEVSharp.DLC.Manager.PreLoadDLCData (string path) inline
Preloads DLC Data into returned DLC class instance.
Todo:
Read actual dlc file/folder
Return data from this file/folder
Definition at line 30 of file DLC/Manager.cs.
References NewDEVSharp.DLC.Manager._dlc, NewDEVSharp.DLC.Manager._verifier, NewDEVSharp.DLC.Verifier.IsDLCLegal(), and NewDEVSharp.DLC.DLC.LoadDLCDataFromPath().
Member Data Documentation
_dlc
readonly DLC NewDEVSharp.DLC.Manager._dlc = new DLC() private
DLC class instance.
See also
NewDEVSharp.DLC.DLC
Definition at line 19 of file DLC/Manager.cs.
Referenced by NewDEVSharp.DLC.Manager.PreLoadDLCData().
_verifier
readonly Verifier NewDEVSharp.DLC.Manager._verifier = new Verifier() private
Verifier class instance.
See also
NewDEVSharp.DLC.Verifier
Definition at line 13 of file DLC/Manager.cs.
Referenced by NewDEVSharp.DLC.Manager.PreLoadDLCData().
The documentation for this class was generated from the following file:
DLC/Manager.cs