Furry Potato: NewDEVSharp.User.Auth Class Reference
NewDEVSharp.User.Auth Class Reference
Class used for user authentication for DLC's
Public Member Functions
override bool ClassInit ()
Class initializer
override string ClassName ()
Class name
void Login (string email, string password)
Login method. Logs user in
void Register (string email, string password)
Register method. Registers a new user
string GetUserData (string uid)
Requests database server to access data of given user by their id
abstract bool ClassInit ()
Class initializer
abstract string ClassName ()
Class name
Private Attributes
readonly Server.Auth _authS = new Server.Auth()
Auth server instance
readonly DataBase _dataBaseS = new DataBase()
Database server instance
Static Private Attributes
const BaseServer.RequestType Post = BaseServer.RequestType.Post
RequestType instance
Detailed Description
Class used for user authentication for DLC's
Todo:
Authorize user
Store encrypted data offline for authentication when user is offline
Definition at line 10 of file User/Auth.cs.
Member Function Documentation
ClassInit()
override bool NewDEVSharp.User.Auth.ClassInit () inline virtual
Class initializer
Returns
true or false whether class was initialized properly or not
Implements NewDEVSharp.BaseClass.
Definition at line 27 of file User/Auth.cs.
References NewDEVSharp.User.Auth._authS, and NewDEVSharp.User.Auth.ClassInit().
Referenced by CSharpCore._Ready(), and NewDEVSharp.User.Auth.ClassInit().
ClassName()
override string NewDEVSharp.User.Auth.ClassName () inline virtual
Class name
Returns
Name of the class
Implements NewDEVSharp.BaseClass.
Definition at line 32 of file User/Auth.cs.
GetUserData()
string NewDEVSharp.User.Auth.GetUserData (string uid) inline
Requests database server to access data of given user by their id
Parameters
uid User ID
Returns
JSON string
See also
BaseServer.RequestType, BaseServer.DictToJson, BaseServer.JsonToStringDict
Todo:
Make the method really returning user data
Definition at line 70 of file User/Auth.cs.
References NewDEVSharp.User.Auth._dataBaseS, NewDEVSharp.User.Auth.Post, and NewDEVSharp.Server.DataBase.Request().
Login()
void NewDEVSharp.User.Auth.Login (string email, string password) inline
Login method. Logs user in
Parameters
email User email
password User password
Todo:
Implement token management. This is just for learning purposes
Implement getting user data, retrieving token
Implement token refresh
Implement returning user data if user was successfully logged in
Definition at line 45 of file User/Auth.cs.
References NewDEVSharp.User.Auth._authS, and NewDEVSharp.User.Auth.Post.
Referenced by CSharpCore._Ready().
Register()
void NewDEVSharp.User.Auth.Register (string email, string password) inline
Register method. Registers a new user
Parameters
email User email
password User password
Todo:
Add registering method
Registering new user MUST BE FUCKING DONE by server :3
Definition at line 59 of file User/Auth.cs.
Member Data Documentation
_authS
readonly Server.Auth NewDEVSharp.User.Auth._authS = new Server.Auth() private
Auth server instance
Definition at line 15 of file User/Auth.cs.
Referenced by NewDEVSharp.User.Auth.ClassInit(), and NewDEVSharp.User.Auth.Login().
_dataBaseS
readonly DataBase NewDEVSharp.User.Auth._dataBaseS = new DataBase() private
Database server instance
Definition at line 20 of file User/Auth.cs.
Referenced by NewDEVSharp.User.Auth.GetUserData().
Post
const BaseServer.RequestType NewDEVSharp.User.Auth.Post = BaseServer.RequestType.Post static private
RequestType instance
Definition at line 25 of file User/Auth.cs.
Referenced by NewDEVSharp.User.Auth.GetUserData(), and NewDEVSharp.User.Auth.Login().
The documentation for this class was generated from the following file:
User/Auth.cs