Furry Potato: FurryPotato.Services.Options Class Reference
FurryPotato.Services.Options Class Reference
Service for handling game options.
Public Member Functions
void SetResolution (int width, int height)
Method for setting resolution @TODO Add resolution validation @TODO Add resolution change.
void SetFullscreen (bool fullscreen)
Sets fullscreen mode @TODO Add fullscreen change.
void SetLanguage (string language)
Sets language @TODO Add language change.
void SetVolume (int volume)
Sets volume @TODO Add volume change.
void SaveOptions ()
Method for saving options @TODO Save options to file.
void LoadOptions ()
Method for loading options @TODO Load options from file.
Private Attributes
bool _fullscreen = true
Boolean for checking if game is in fullscreen mode.
string _language = "en"
Language code.
int _resolutionHeight = 1080
Resolution height.
int _resolutionWidth = 1920
Resolution width.
int _volume = 100
Volume.
Detailed Description
Service for handling game options.
Definition at line 13 of file Options.cs.
Member Function Documentation
LoadOptions()
void FurryPotato.Services.Options.LoadOptions () inline
Method for loading options @TODO Load options from file.
Definition at line 88 of file Options.cs.
References FurryPotato.Services.Options.SetFullscreen(), FurryPotato.Services.Options.SetLanguage(), FurryPotato.Services.Options.SetResolution(), and FurryPotato.Services.Options.SetVolume().
SaveOptions()
void FurryPotato.Services.Options.SaveOptions () inline
Method for saving options @TODO Save options to file.
Definition at line 82 of file Options.cs.
SetFullscreen()
void FurryPotato.Services.Options.SetFullscreen (bool fullscreen) inline
Sets fullscreen mode @TODO Add fullscreen change.
Parameters
fullscreen Boolean
Definition at line 56 of file Options.cs.
References FurryPotato.Services.Options._fullscreen.
Referenced by FurryPotato.Services.Options.LoadOptions().
SetLanguage()
void FurryPotato.Services.Options.SetLanguage (string language) inline
Sets language @TODO Add language change.
Parameters
language Language code
Definition at line 65 of file Options.cs.
References FurryPotato.Services.Options._language.
Referenced by FurryPotato.Services.Options.LoadOptions().
SetResolution()
void FurryPotato.Services.Options.SetResolution (int width, int height) inline
Method for setting resolution @TODO Add resolution validation @TODO Add resolution change.
Parameters
width Width in pixels
height Height in pixels
Definition at line 46 of file Options.cs.
References FurryPotato.Services.Options._resolutionHeight, and FurryPotato.Services.Options._resolutionWidth.
Referenced by FurryPotato.Services.Options.LoadOptions().
SetVolume()
void FurryPotato.Services.Options.SetVolume (int volume) inline
Sets volume @TODO Add volume change.
Parameters
volume Volume to set
Definition at line 74 of file Options.cs.
References FurryPotato.Services.Options._volume.
Referenced by FurryPotato.Services.Options.LoadOptions().
Member Data Documentation
_fullscreen
bool FurryPotato.Services.Options._fullscreen = true private
Boolean for checking if game is in fullscreen mode.
Definition at line 17 of file Options.cs.
Referenced by FurryPotato.Services.Options.SetFullscreen().
_language
string FurryPotato.Services.Options._language = "en" private
Language code.
Definition at line 22 of file Options.cs.
Referenced by FurryPotato.Services.Options.SetLanguage().
_resolutionHeight
int FurryPotato.Services.Options._resolutionHeight = 1080 private
Resolution height.
Definition at line 27 of file Options.cs.
Referenced by FurryPotato.Services.Options.SetResolution().
_resolutionWidth
int FurryPotato.Services.Options._resolutionWidth = 1920 private
Resolution width.
Definition at line 32 of file Options.cs.
Referenced by FurryPotato.Services.Options.SetResolution().
_volume
int FurryPotato.Services.Options._volume = 100 private
Volume.
Definition at line 37 of file Options.cs.
Referenced by FurryPotato.Services.Options.SetVolume().
The documentation for this class was generated from the following file:
Options.cs