Furry Potato: NewDEVSharp.Core Class Reference
NewDEVSharp.Core Class Reference
Core class used to hold and manage all of the properties
Public Member Functions
DLCManager GetDLCManager ()
Private Member Functions
void Init ()
Class initializer
void InitSubClass (BaseClass className)
Initializes all other classes
Private Attributes
Dictionary< string, bool > _initializedClasses = new Dictionary<string, bool>()
list of initialized and not initialized classes
DLCManager _dlcManager = null
DLCManager class instance
Detailed Description
Core class used to hold and manage all of the properties
Definition at line 10 of file Core.cs.
Member Function Documentation
GetDLCManager()
DLCManager NewDEVSharp.Core.GetDLCManager () inline
Definition at line 42 of file Core.cs.
References NewDEVSharp.Core._dlcManager.
Referenced by CSharpCore._Ready().
Init()
void NewDEVSharp.Core.Init () inline private
Class initializer
Definition at line 26 of file Core.cs.
References NewDEVSharp.Core.InitSubClass().
InitSubClass()
void NewDEVSharp.Core.InitSubClass (BaseClass className) inline private
Initializes all other classes
Parameters
className Class instance
Definition at line 35 of file Core.cs.
References NewDEVSharp.Core._dlcManager, NewDEVSharp.Core._initializedClasses, NewDEVSharp.BaseClass.ClassInit(), and NewDEVSharp.BaseClass.ClassName().
Referenced by NewDEVSharp.Core.Init().
Member Data Documentation
_dlcManager
DLCManager NewDEVSharp.Core._dlcManager = null private
DLCManager class instance
Definition at line 20 of file Core.cs.
Referenced by NewDEVSharp.Core.GetDLCManager(), and NewDEVSharp.Core.InitSubClass().
_initializedClasses
Dictionary<string, bool> NewDEVSharp.Core._initializedClasses = new Dictionary<string, bool>() private
list of initialized and not initialized classes
Definition at line 15 of file Core.cs.
Referenced by NewDEVSharp.Core.InitSubClass().
The documentation for this class was generated from the following file:
Core.cs