Furry Potato: SaveContainer Class Reference
SaveContainer Class Reference
Class that creates save data
Public Member Functions
override void SetSaveDir (string baseDir)
Sets save root directory
override void WriteDirectories (Dictionary< string, Dictionary< string, string > > data)
Creates all necessary directories
override void WriteData (string subfolder, System.Collections.Generic.Dictionary< string, string > data)
This function writes data to file according to data type, path and object that will hold this data
abstract void SetSaveDir (string baseDir)
Sets save root directory
abstract void WriteDirectories (Dictionary< string, Dictionary< string, string > > dirData)
Creates all necessary directories
abstract void WriteData (string subfolder, System.Collections.Generic.Dictionary< string, string > data)
Writes passes in as arguments save data
Private Attributes
string _saveRoot = ""
Detailed Description
Class that creates save data
Definition at line 8 of file SaveContainer.cs.
Member Function Documentation
SetSaveDir()
override void SaveContainer.SetSaveDir (string baseDir) inline virtual
Sets save root directory
Parameters
baseDir Root directory
Implements BaseSave.
Definition at line 15 of file SaveContainer.cs.
References _saveRoot.
Referenced by Saver.SaveGame().
WriteData()
override void SaveContainer.WriteData (string subfolder, System.Collections.Generic.Dictionary< string, string > data) inline virtual
This function writes data to file according to data type, path and object that will hold this data
Parameters
subfolder Subfolder name. It usually comes with type prefix, but prefix will be removed by this function
data Dictionary of data
Implements BaseSave.
Definition at line 38 of file SaveContainer.cs.
References _saveRoot.
Referenced by Saver.SaveGame().
WriteDirectories()
override void SaveContainer.WriteDirectories (Dictionary< string, Dictionary< string, string > > data) inline virtual
Creates all necessary directories
Parameters
data Data to create directories from
Exceptions
InvalidOperationException Exception, when directory can not be created
Implements BaseSave.
Definition at line 24 of file SaveContainer.cs.
References _saveRoot.
Referenced by Saver.SaveGame().
Member Data Documentation
_saveRoot
string SaveContainer._saveRoot = "" private
Definition at line 9 of file SaveContainer.cs.
Referenced by SetSaveDir(), WriteData(), and WriteDirectories().
The documentation for this class was generated from the following file:
SaveContainer.cs