Furry Potato: ShopItemManager Class Reference
ShopItemManager Class Reference
Class for managing all shop items
Public Member Functions
void InitItems ()
Initializes all shop items. Needs to be called before everything
Array< string > GetItemList ()
Returns array of items in shops. Includes only item names for reference to load their data in Godot and display them in game
Dictionary< string, string > GetItemData (string itemName)
Returns item data for given item.
Private Attributes
System.Collections.Generic.Dictionary< string, ShopItemBase > _shopItems = new System.Collections.Generic.Dictionary<string, ShopItemBase>()
Dictionary of items in shops. Includes item name and it's instance. string includes item name, and
readonly ShopItemBase _casualHeadphones = new ShopItemHeadphones()
Array< string > _itemList = new Array<string>()
Array of items in shops. Includes only item names for reference to load their data in Godot and display them in game
Detailed Description
Class for managing all shop items
Definition at line 9 of file ShopItemManager.cs.
Member Function Documentation
GetItemData()
Dictionary< string, string > ShopItemManager.GetItemData (string itemName) inline
Returns item data for given item.
Parameters
itemName Item name
Returns
Item data in dictionary
Definition at line 46 of file ShopItemManager.cs.
References _shopItems.
GetItemList()
Array< string > ShopItemManager.GetItemList () inline
Returns array of items in shops. Includes only item names for reference to load their data in Godot and display them in game
Returns
List of in shop items
Definition at line 36 of file ShopItemManager.cs.
References _itemList.
InitItems()
void ShopItemManager.InitItems () inline
Initializes all shop items. Needs to be called before everything
Definition at line 25 of file ShopItemManager.cs.
References _itemList, and _shopItems.
Member Data Documentation
_casualHeadphones
readonly ShopItemBase ShopItemManager._casualHeadphones = new ShopItemHeadphones() private
Definition at line 16 of file ShopItemManager.cs.
_itemList
Array<string> ShopItemManager._itemList = new Array<string>() private
Array of items in shops. Includes only item names for reference to load their data in Godot and display them in game
Definition at line 21 of file ShopItemManager.cs.
Referenced by GetItemList(), and InitItems().
_shopItems
System.Collections.Generic.Dictionary<string, ShopItemBase> ShopItemManager._shopItems = new System.Collections.Generic.Dictionary<string, ShopItemBase>() private
Dictionary of items in shops. Includes item name and it's instance. string includes item name, and
ShopItemBase it's instance
Definition at line 14 of file ShopItemManager.cs.
Referenced by GetItemData(), and InitItems().
The documentation for this class was generated from the following file:
scripts/scenes/game/shop/ShopItemManager.cs