Furry Potato: SaveManager Class Reference
SaveManager Class Reference
Class used to manage all game saves.
Public Member Functions
override void _Ready ()
Array< string > GetSaveNamesArray ()
Public interface for getting list of save names
string GetSaveLastModificationDate (string saveName)
Public interface for getting save modification date
Public Attributes
int SaveCount = 0
Array that contains only list of save names
Dictionary< string, string > SavePaths = new Dictionary<string, string>()
Dictionary that contains save name as key and path to root of save as a value
Private Member Functions
void GetSaveList ()
Loads all save names from disk
Private Attributes
Array< string > _saveNamesList = new Array<string>()
Detailed Description
Class used to manage all game saves.
Definition at line 11 of file SaveManager.cs.
Member Function Documentation
_Ready()
override void SaveManager._Ready () inline
Definition at line 21 of file SaveManager.cs.
References GetSaveList().
Referenced by SaveSelectMenuPopup._Ready().
GetSaveLastModificationDate()
string SaveManager.GetSaveLastModificationDate (string saveName) inline
Public interface for getting save modification date
Parameters
saveName Name of the save
Returns
Last modification date in string
Definition at line 59 of file SaveManager.cs.
Referenced by SaveSelectMenuPopup._Ready().
GetSaveList()
void SaveManager.GetSaveList () inline private
Loads all save names from disk
Definition at line 29 of file SaveManager.cs.
References _saveNamesList, SaveCount, and SavePaths.
Referenced by _Ready().
GetSaveNamesArray()
Array< string > SaveManager.GetSaveNamesArray () inline
Public interface for getting list of save names
Returns
Array of save names
Definition at line 50 of file SaveManager.cs.
References _saveNamesList.
Referenced by SaveSelectMenuPopup._Ready().
Member Data Documentation
_saveNamesList
Array<string> SaveManager._saveNamesList = new Array<string>() private
Definition at line 16 of file SaveManager.cs.
Referenced by GetSaveList(), and GetSaveNamesArray().
SaveCount
int SaveManager.SaveCount = 0
Array that contains only list of save names
Definition at line 15 of file SaveManager.cs.
Referenced by SaveSelectMenuPopup._Ready(), and GetSaveList().
SavePaths
Dictionary<string, string> SaveManager.SavePaths = new Dictionary<string, string>()
Dictionary that contains save name as key and path to root of save as a value
Definition at line 20 of file SaveManager.cs.
Referenced by SaveSelectMenuPopup._Ready(), and GetSaveList().
The documentation for this class was generated from the following file:
SaveManager.cs