Furry Potato: PartyRatingsMenu Class Reference
PartyRatingsMenu Class Reference
This class controls Party Ratings menu including displaying and showing rating details
Public Member Functions
override void _Ready ()
Public Attributes
Dictionary< string, string > ratingsList = new Dictionary<string, string>()
This dictionary stands for {party_id: rating}
Dictionary< string, string > ratingsClubs = new Dictionary<string, string>()
This dictionary stands for {party_id: club}
Private Member Functions
void DisplayRatings ()
Method to display ratings in the list
Private Attributes
PartyList _itemList
Item list instance, used to display ratings list.
Detailed Description
This class controls Party Ratings menu including displaying and showing rating details
Todo:
Implement getting list of the clubs and assign them to party id's
Implement getting list of ratings from each party and assign them to party id's
Fix refreshing party lists each time window is about to be shown
Definition at line 10 of file PartyRatingsMenu.cs.
Member Function Documentation
_Ready()
override void PartyRatingsMenu._Ready () inline
Definition at line 27 of file PartyRatingsMenu.cs.
References _itemList, DisplayRatings(), and ratingsList.
DisplayRatings()
void PartyRatingsMenu.DisplayRatings () inline private
Method to display ratings in the list
Definition at line 46 of file PartyRatingsMenu.cs.
References _itemList, ratingsClubs, and ratingsList.
Referenced by _Ready().
Member Data Documentation
_itemList
PartyList PartyRatingsMenu._itemList private
Item list instance, used to display ratings list.
Definition at line 25 of file PartyRatingsMenu.cs.
Referenced by _Ready(), and DisplayRatings().
ratingsClubs
Dictionary<string, string> PartyRatingsMenu.ratingsClubs = new Dictionary<string, string>()
This dictionary stands for {party_id: club}
Definition at line 20 of file PartyRatingsMenu.cs.
Referenced by PartyRatingDetails.DisplayDetailedRating(), and DisplayRatings().
ratingsList
Dictionary<string, string> PartyRatingsMenu.ratingsList = new Dictionary<string, string>()
This dictionary stands for {party_id: rating}
Definition at line 15 of file PartyRatingsMenu.cs.
Referenced by _Ready(), and DisplayRatings().
The documentation for this class was generated from the following file:
PartyRatingsMenu.cs