Furry Potato: SaveSelectMenuPopup Class Reference
SaveSelectMenuPopup Class Reference
Class used by save menu popup
Public Member Functions
override void _Ready ()
Public Attributes
Dictionary< string, Dictionary< string, string > > PreloadedSaveData = new Dictionary<string, Dictionary<string, string>>()
Contains preloaded save data, previously set by
Protected Member Functions
void SaveSelectedToLoad (int index)
Called by Godot, when user has selected save to load
Private Member Functions
delegate void SaveDataPreloaded ()
Signal emitted when save data has been preloaded
Private Attributes
ItemList _itemList
ItemList's node instance
readonly SaveManager _saveManager = new SaveManager()
SaveManager instance
Dictionary< int, string > _pathsForItemList = new Dictionary<int, string>()
Dictionary used to keep where is root path for each save. To make it easier the key is id of ItemList's item.
int _currentItemListId = 0
Current ID of next non-existent Item in the ItemList
Detailed Description
Class used by save menu popup
Definition at line 8 of file SaveSelectMenuPopup.cs.
Member Function Documentation
_Ready()
override void SaveSelectMenuPopup._Ready () inline
Definition at line 41 of file SaveSelectMenuPopup.cs.
References _currentItemListId, _itemList, _pathsForItemList, SaveManager._Ready(), _saveManager, SaveManager.GetSaveLastModificationDate(), SaveManager.GetSaveNamesArray(), SaveManager.SaveCount, and SaveManager.SavePaths.
SaveDataPreloaded()
delegate void SaveSelectMenuPopup.SaveDataPreloaded () private
Signal emitted when save data has been preloaded
SaveSelectedToLoad()
void SaveSelectMenuPopup.SaveSelectedToLoad (int index) inline protected
Called by Godot, when user has selected save to load
Parameters
index Index of item, in displayed ItemList with save list, that contains selected save name
Definition at line 62 of file SaveSelectMenuPopup.cs.
References _pathsForItemList, Loader.LoadSave(), and PreloadedSaveData.
Member Data Documentation
_currentItemListId
int SaveSelectMenuPopup._currentItemListId = 0 private
Current ID of next non-existent Item in the ItemList
Definition at line 40 of file SaveSelectMenuPopup.cs.
Referenced by _Ready().
_itemList
ItemList SaveSelectMenuPopup._itemList private
ItemList's node instance
Definition at line 19 of file SaveSelectMenuPopup.cs.
Referenced by _Ready().
_pathsForItemList
Dictionary<int, string> SaveSelectMenuPopup._pathsForItemList = new Dictionary<int, string>() private
Dictionary used to keep where is root path for each save. To make it easier the key is id of ItemList's item.
Definition at line 35 of file SaveSelectMenuPopup.cs.
Referenced by _Ready(), and SaveSelectedToLoad().
_saveManager
readonly SaveManager SaveSelectMenuPopup._saveManager = new SaveManager() private
SaveManager instance
Definition at line 30 of file SaveSelectMenuPopup.cs.
Referenced by _Ready().
PreloadedSaveData
Dictionary<string, Dictionary<string, string> > SaveSelectMenuPopup.PreloadedSaveData = new Dictionary<string, Dictionary<string, string>>()
Contains preloaded save data, previously set by
new Loader().LoadSave(string path) Useful after only SaveDataPreloaded signal has been called.
Definition at line 25 of file SaveSelectMenuPopup.cs.
Referenced by SaveSelectedToLoad().
The documentation for this class was generated from the following file:
SaveSelectMenuPopup.cs