Furry Potato: NewDEVSharp.Utils.MP3.DataTags Class Reference
NewDEVSharp.Utils.MP3.DataTags Class Reference
Class for holding MP3 Data Types
Public Member Functions
override bool ClassInit ()
Class initializer
override string ClassName ()
Class name
override void SetExtension (string newExtension)
Sets an extension
IPicture Image (string path)
Returns cover art data
string Title (string path)
Returns title data
string Author (string path)
Returns author data
string Album (string path)
Returns album data
string Copyright (string path)
Returns copyright data
Public Member Functions inherited from NewDEVSharp.Utils.MusicUtils
override bool ClassInit ()
Class initializer
override string ClassName ()
Class name
abstract void SetExtension (string newExtension)
Sets an extension
string GetExtension ()
Returns extension used by utils class for specified file type
abstract bool ClassInit ()
Class initializer
abstract string ClassName ()
Class name
Additional Inherited Members
Protected Attributes inherited from NewDEVSharp.Utils.MusicUtils
Core Core = new Core()
string Extension = ""
Holds for us extension info
Detailed Description
Class for holding MP3 Data Types
Definition at line 9 of file MP3/DataTags.cs.
Member Function Documentation
Album()
string NewDEVSharp.Utils.MP3.DataTags.Album (string path) inline
Returns album data
Parameters
path Path to the mp3 file
Returns
Returns album data of type string
Definition at line 60 of file MP3/DataTags.cs.
Author()
string NewDEVSharp.Utils.MP3.DataTags.Author (string path) inline
Returns author data
Parameters
path Path to the mp3 file
Returns
Returns author data of type string
Definition at line 50 of file MP3/DataTags.cs.
ClassInit()
override bool NewDEVSharp.Utils.MP3.DataTags.ClassInit () inline virtual
Class initializer
Returns
true or false whether class was initialized properly or not
Implements NewDEVSharp.BaseClass.
Definition at line 11 of file MP3/DataTags.cs.
References NewDEVSharp.Core.InitFmod(), and NewDEVSharp.Utils.MP3.DataTags.SetExtension().
ClassName()
override string NewDEVSharp.Utils.MP3.DataTags.ClassName () inline virtual
Class name
Returns
Name of the class
Implements NewDEVSharp.BaseClass.
Definition at line 17 of file MP3/DataTags.cs.
Copyright()
string NewDEVSharp.Utils.MP3.DataTags.Copyright (string path) inline
Returns copyright data
Parameters
path Path to the mp3 file
Returns
Returns copyright data of type string
Definition at line 70 of file MP3/DataTags.cs.
Image()
IPicture NewDEVSharp.Utils.MP3.DataTags.Image (string path) inline
Returns cover art data
Parameters
path Path to the mp3 file
Returns
Returns cover art data of type TagLib.IPicture
Definition at line 30 of file MP3/DataTags.cs.
Referenced by CustomAudioLibrary.LoadSongFiles().
SetExtension()
override void NewDEVSharp.Utils.MP3.DataTags.SetExtension (string newExtension) inline virtual
Sets an extension
Parameters
newExtension New extension in string, eg '.mp3'
Implements NewDEVSharp.Utils.MusicUtils.
Definition at line 21 of file MP3/DataTags.cs.
References NewDEVSharp.Utils.MusicUtils.Extension.
Referenced by NewDEVSharp.Utils.MP3.DataTags.ClassInit().
Title()
string NewDEVSharp.Utils.MP3.DataTags.Title (string path) inline
Returns title data
Parameters
path Path to the mp3 file
Returns
Returns title data of type string
Definition at line 40 of file MP3/DataTags.cs.
The documentation for this class was generated from the following file:
MP3/DataTags.cs